#!/usr/bin/env bash
# The following bash script transfers a file from the client to a server

# Checking if all the required parameters are provided
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
