#!/usr/bin/env bash
# The following script installs nginx server on ubuntu
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

# Updating the package list and installing Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configuring theFireWall (UFW)
sudo ufw allow 'Nginx HTTP'

# Creating a default HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configuring Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    server_name _;
    location / {
        root /var/www/html;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Creating a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Removing the default Nginx welcome page
sudo rm /etc/nginx/sites-enabled/default

# Testing for syntax error
sudo nginx -t

# Making sure Nginx's running
sudo service nginx restart
