#!/usr/bin/env bash
# The following script installs nginx server on ubuntu
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

# Updating the package list and install Nginx
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx

# Creating a default HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo ufw allow 'Nginx HTTP'

# Making sure Nginx is running
sudo service nginx restart
