#!/usr/bin/env bash
# The following script configures Nginx server so that
# /redirect_me is redirecting to another page

# Installing Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Creating a default HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Defining the configuration string for the redirection
replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Using sed to replace the default Nginx configuration with the redirection configuration
sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-available/default

# Restarting the Nginx service to apply the new configuration
sudo service nginx restart
