#!/usr/bin/env bash
# The following script pings an IP Address passed as an argument
# it should:
# Accept a string as an argument
# Display "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if no argument passed
# Ping the IP 5 times

if [ "$#" -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi
ping -c 5 "$1"
