#!/usr/bin/env bash
# The following script is doing the following:

#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# get the current PIDand write it to the PID file
echo $$ > /var/run/myscript.pid

# display "To infinity and beyond" indefinitely
while true; do
	echo "To infinity and beyond"
	sleep 2
done

# trap SIGTERM signal to display the given message and clean up
trap "echo 'I hate the kill command' && cleanup" SIGTERM

# trap SIGINT signal to display a message
trap "echo 'Y U no love me?!'" SIGINT

# Deletes the pid file and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT
