#!/usr/bin/env bash
# The following Script loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
itr=1
while [ "$itr" -le 10 ]
do
	if [ "${itr}" -eq 4 ]
	then
		echo "bad luck"
	elif [ "${itr}" -eq 8 ]
        then
                echo "good luck"
	else
		echo "Best School"
	fi
	((itr++))
done
