#!/usr/bin/env bash
# The following script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

list=$(ls)
for ctr in ${list}
do
	echo "${ctr}" | cut -d "-" -f 2;
done
