#!/usr/bin/env bash
# The following script is the SSH client configuration
# SSH must be configured to use the private key ~/.ssh/school
# SSH must be configured to refuse to authenticate using a password
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
